### ISSUE TITLE
lerna bootstrap failing

### ISSUE THREAD

**Issue by ischorr** [xesf/castaway#2]
On Debian buster, freshly installed yarn and lerna, freshly downloaded master:

$ lerna bootstrap
lerna notice cli v3.20.2
lerna info Bootstrapping 5 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 2 in '@castaway/lifeboat'
lerna ERR! npm install exited 2 in '@castaway/lifeboat'

**Comment by ischorr** [comment]
Turns out this was a problem caused by installing the default nodejs package from debian repos - it's nodejs v10, and didn't even include npm.  So it was failing for a variety of reasons.

I had to fiddle a bit to find a working solution - eventually got the nodesource package installed, although I had to run as root (not with sudo, but in a root shell session) and needed to run yarn update in the castaway root before lerna bootstrap would run right.

The dump project is working now, I'm still looking into issues with the viewer (which I'm more interested in, although the dump helps a bit with something else I was looking into).  Looks like really great work so far!

I'd opened this because I thought maybe there was something missing in the setup instructions.  Not the problem I thought it was, but a couple suggestions as someone setting this up for the first time:

- Might want to mention that RESOUCE.MAP and RESOURCE.001 need to be in /data subdir of the castaway root
- looks like "yarn global add lerna" really wants to be run as root (sudo's fine), otherwise it installs in user homedir and probably requires environmental setup and other things to work right.

**Comment by xesf** [comment]
Hey,

Thanks for looking at the project. I will do those suggestions.

The project structure is a bit weird I can say, not really happy with it.
I have been thinking about the project lately again and thought about focusing on just getting the scenes working correctly to support the story mode and have the viewer as a separate app.
There are some serious issues with JS obj reference due to the way I did the state object and that causes some weird behaviours in the scenes. That part needs a completely knew approach.

I am interesting to know what you plan to do with the project. Let me know if you get some progress.

Cheers,

**Comment by xesf** [comment]
Lerna no longer used
